<script lang="ts">
import { H5 } from "lube-ui"
import JsMap from "cells/typography/JsMap.svelte"
import CodePage from "organs/@common/utils/CodePage.svelte"
</script>

<svelte:head>
	<title>Shorthand Keys | CSS Lube</title>
</svelte:head>

<H5>Shorthand Keys</H5>
<div class="h=1"></div>
<span>Shorthand Keys of CSS Lube.</span><br>
<div class="h=2"></div>
<CodePage>
	<JsMap
		name="shorthandForProperties"
		json={`[
	["acc", "accent-color"],
	["ac", "align-content"],
	["ai", "align-items"],
	["as", "align-self"],
	["a", "animation"],
	["bf", "backdrop-filter"],
	["bg", "background"],
	["bgc", "background-color"],
	["bgi", "background-image"],
	["bd", "border"],
	["bdb", "border-bottom"],
	["bdc", "border-color"],
	["bdl", "border-left"],
	["br", "border-radius"],
	["bdr", "border-right"],
	["bds", "border-style"],
	["bdt", "border-top"],
	["bdw", "border-width"],
	["b", "bottom"],
	["bs", "box-shadow"],
	["cp", "clip-path"],
	["c", "color"],
	["ct", "content"],
	["cs", "cursor"],
	["d", "display"],
	["f", "fill"],
	["ft", "filter"],
	["fg", "flex-grow"],
	["fsk", "flex-shrink"],
	["fw", "flex-wrap"],
	["fl", "float"],
	["ff", "font-family"],
	["fs", "font-size"],
	["fv", "font-variant"],
	["g", "gap"],
	["gc", "grid-column"],
	["gr", "grid-row"],
	["gtc", "grid-template-columns"],
	["gtr", "grid-template-rows"],
	["h", "height"],
	["i", "inset"],
	["is", "isolation"],
	["jc", "justify-content"],
	["l", "left"],
	["lsp", "letter-spacing"],
	["lb", "line-break"],
	["lh", "line-height"],
	["ls", "list-style"],
	["m", "margin"],
	["mb", "margin-bottom"],
	["ml", "margin-left"],
	["mr", "margin-right"],
	["mt", "margin-top"],
	["xh", "max-height"],
	["xw", "max-width"],
	["mh", "min-height"],
	["mw", "min-width"],
	["mbm", "mix-blend-mode"],
	["of", "object-fit"],
	["op", "opacity"],
	["ol", "outline"],
	["o", "overflow"],
	["ow", "overflow-wrap"],
	["ox", "overflow-x"],
	["oy", "overflow-y"],
	["p", "padding"],
	["pb", "padding-bottom"],
	["pi", "padding-inline"],
	["pl", "padding-left"],
	["pr", "padding-right"],
	["pt", "padding-top"],
	["ps", "perspective"],
	["pso", "perspective-origin"],
	["rs", "resize"],
	["r", "right"],
	["ssa", "scroll-snap-align"],
	["sst", "scroll-snap-type"],
	["so", "shape-outside"],
	["tz", "tab-size"],
	["tl", "table-layout"],
	["ta", "text-align"],
	["td", "text-decoration"],
	["ts", "text-shadow"],
	["ttf", "text-transform"],
	["t", "top"],
	["tf", "transform"],
	["tfo", "transform-origin"],
	["tt", "transition"],
	["us", "user-select"],
	["va", "vertical-align"],
	["v", "visibility"],
	["ws", "white-space"],
	["w", "width"],
	["wc", "will-change"],
	["wb", "word-break"],
	["wsp", "word-spacing"],
	["ww", "word-wrap"],
	["wm", "writing-mode"],
	["z", "z-index"]
]`}/>
</CodePage>